# This is a basic workflow to help you get started with Actions

name: Docker APR Base CI

# Controls when the workflow will run
on:
  workflow_dispatch:

env:
  APR_VERSION_ARG: 1.7.6
  APR_ICONV_VERSION_ARG: 1.2.2
  APR_UTIL_VERSION_ARG: 1.6.3

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  alpine:
    # The type of runner that the job will run on
    runs-on: ubuntu-22.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: ${{ secrets.REPOSITORY }}
          token: ${{ secrets.GH_PAT }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./apr/base/alpine
          build-args: |
            APR_VERSION_ARG=${{ env.APR_VERSION_ARG }}
            APR_ICONV_VERSION_ARG=${{ env.APR_ICONV_VERSION_ARG }}
            APR_UTIL_VERSION_ARG=${{ env.APR_UTIL_VERSION_ARG }}
          push: true
          platforms: linux/amd64,linux/arm64/v8,linux/ppc64le,linux/s390x
          tags: dph5199278/apr:${{ env.APR_VERSION_ARG }}-alpine,dph5199278/apr:alpine-base
  debian:
    # The type of runner that the job will run on
    runs-on: ubuntu-22.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: ${{ secrets.REPOSITORY }}
          token: ${{ secrets.GH_PAT }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./apr/base/debian
          build-args: |
            APR_VERSION_ARG=${{ env.APR_VERSION_ARG }}
            APR_ICONV_VERSION_ARG=${{ env.APR_ICONV_VERSION_ARG }}
            APR_UTIL_VERSION_ARG=${{ env.APR_UTIL_VERSION_ARG }}
          push: true
          platforms: linux/amd64,linux/arm64/v8,linux/ppc64le,linux/s390x
          tags: dph5199278/apr:${{ env.APR_VERSION_ARG }},dph5199278/apr:base,dph5199278/apr:latest
